# We don't need cache yet
#cache:
#  key: ${CI_COMMIT_REF_SLUG}
#  paths:
#    - TODO

#-----------------------------------------------------------------------------#
#
# General startup commands
#
#-----------------------------------------------------------------------------#
before_script:
    - git submodule init
    - git submodule update

#-----------------------------------------------------------------------------#
#
# Top level tests
#
#-----------------------------------------------------------------------------#
All-Bottom:
  script:
    - nix-shell tool-suite/nix/dev/gfe.nix --run './top_level_make.sh bottom'
  tags: ["voting-system"]

All-Typecheck:
  script:
    - nix-shell tool-suite/nix/dev/gfe.nix --run './top_level_make.sh typecheck'
  tags: ["voting-system"]

All-Verify:
  script:
    - nix-shell tool-suite/nix/dev/gfe.nix --run './top_level_make.sh verify'
  tags: ["voting-system"]

All-Freertos:
  script:
    - nix-shell tool-suite/nix/dev/gfe.nix --run './top_level_make.sh freertos'
  tags: ["voting-system"]

All-Tests:
  script:
    - nix-shell tool-suite/nix/dev/gfe.nix --run './top_level_make.sh tests'
  tags: ["voting-system"]
