# We don't need cache yet
#cache:
#  key: ${CI_COMMIT_REF_SLUG}
#  paths:
#    - TODO

#-----------------------------------------------------------------------------#
#
# General startup commands
#
#-----------------------------------------------------------------------------#
before_script:
    - git submodule init
    - git submodule update

#-----------------------------------------------------------------------------#
#
# Top level tests
#
#-----------------------------------------------------------------------------#
Bottom:
  script:
    - export TARGET=bottom
    - nix-shell tool-suite/nix/dev/gfe.nix --run 'make bottom_all'
  tags: ["voting-system"]

Typecheck:
  script:
    - export TARGET=verification
    - nix-shell tool-suite/nix/dev/gfe.nix --run 'make typecheck_all'
  tags: ["voting-system"]

Verify:
  script:
    - export TARGET=verification
    - nix-shell tool-suite/nix/dev/gfe.nix --run 'make verify_all'
  tags: ["voting-system"]

Freertos:
  script:
    - export TARGET=freertos
    - nix-shell tool-suite/nix/dev/gfe.nix --run 'make freertos_all'
  tags: ["voting-system"]

HostTests:
  script:
    - export TARGET=hosttests
    - nix-shell tool-suite/nix/dev/gfe.nix --run 'make hosts_all'
  tags: ["voting-system"]

Simulator:
  script:
    - export TARGET=sim
    - nix-shell tool-suite/nix/dev/gfe.nix --run 'make sim_all'
  tags: ["voting-system"]