# We don't need cache yet
#cache:
#  key: ${CI_COMMIT_REF_SLUG}
#  paths:
#    - TODO

#-----------------------------------------------------------------------------#
#
# General startup commands
#
#-----------------------------------------------------------------------------#
before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab-ext.galois.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - export USER=gitlab-runner

#-----------------------------------------------------------------------------#
#
# Smart ballot box
#
#-----------------------------------------------------------------------------#
SBB-Bottom:
  script:
    - nix-shell tool-suite/nix/dev/gfe.nix --run 'cd source/sbb; export TARGET=bottom; make; make clean;'
  tags: ["voting-system"]
  only:
    - master
  except:
    - schedules

SBB-FreeRTOS:
  script:
    - nix-shell tool-suite/nix/dev/gfe.nix --run 'cd source/sbb; export TARGET=freertos; make; make clean;'
  tags: ["voting-system"]
  only:
    - master
  except:
    - schedules

SBB-Verification:
  script:
    - nix-shell tool-suite/nix/dev/gfe.nix --run 'cd source/sbb; export TARGET=verification; make; make clean;'
  tags: ["voting-system"]
  only:
    - master
  except:
    - schedules