# We don't need cache yet
#cache:
#  key: ${CI_COMMIT_REF_SLUG}
#  paths:
#    - TODO

#-----------------------------------------------------------------------------#
#
# General startup commands
#
#-----------------------------------------------------------------------------#
before_script:
    - git submodule init
    - git submodule update

#-----------------------------------------------------------------------------#
#
# Top level tests
#
#-----------------------------------------------------------------------------#
Bottom:
  script:
    - nix-shell tool-suite/nix/dev/gfe.nix --run 'export TARGET=bottom make bottom_all'
  tags: ["voting-system"]

Typecheck:
  script:
    - nix-shell tool-suite/nix/dev/gfe.nix --run 'export TARGET=verification make typecheck_all'
  tags: ["voting-system"]

Verify:
  script:
    - nix-shell tool-suite/nix/dev/gfe.nix --run 'export TARGET=verification make verify_all'
  tags: ["voting-system"]

Freertos:
  script:
    - nix-shell tool-suite/nix/dev/gfe.nix --run 'export TARGET=freertos make freertos_all'
  tags: ["voting-system"]

HostTests:
  script:
    - nix-shell tool-suite/nix/dev/gfe.nix --run 'export TARGET=hosttests make hosts_all'
  tags: ["voting-system"]

Simulator:
  script:
    - nix-shell tool-suite/nix/dev/gfe.nix --run 'export TARGET=sim make sim_all'
  tags: ["voting-system"]