INCLUDES = -I. \
	-I../../FreeRTOS-mirror/FreeRTOS/Demo/RISC-V_Galois_P1 \
	-I../../FreeRTOS-mirror/FreeRTOS/Source/include \
	-I../../FreeRTOS-mirror/FreeRTOS/Source/portable/GCC/RISC-V \
	-I../../FreeRTOS-mirror/FreeRTOS/Demo/RISC-V_Galois_P1/demo \
	-I../../FreeRTOS-mirror/FreeRTOS/Demo/RISC-V_Galois_P1/bsp \
	-I../../FreeRTOS-mirror/FreeRTOS/Demo/RISC-V_Galois_P1/devices

# Build the bottom target
log_bottom:
	cd $(LOG_DIR) && \
	$(CC) $(CFLAGS) -D__riscv_xlen=32 log_main.c log_bottom.c secure_log_bottom.c log_t.c secure_log_t.c log_io.c log_net.c $(OS_DIR)/log_fs.c $(OS_DIR)/log_net_osd.c $(OS_DIR)/debug_io.c ../crypto/crypto_t.c ../crypto/base64.c ../crypto/crypto_bottom.c -o secure_log_bottom.elf && \
	rm -f *.o $(OS_DIR)/*.o

log_bottom_clean:
	cd $(LOG_DIR) && \
	rm -f secure_log_bottom.elf
