# Makefile for Building the crypto subsystem "host" tests - e.g. tests that run on Linux or MacOS
HOSTTEST_CFLAGS += -I $(INCLUDE_DIR)/crypto

crypto_hosttest_all: crypto_hosttest1 crypto_hosttest2 crypto_hosttest3 crypto_hosttest4 crypto_hosttest5 crypto_base64test

CRYPTO_SOURCE = $(CRYPTO_SRC) $(CRYPTO_DIR)/crypto_config_default.c

crypto_hosttest1:
	$(CC) $(HOSTTEST_CFLAGS) -o hosttest1 hosttest1.c $(CRYPTO_SOURCE)

crypto_hosttest2:
	$(CC) $(HOSTTEST_CFLAGS) -o hosttest2 hosttest2.c $(CRYPTO_SOURCE)

crypto_hosttest3:
	$(CC) $(HOSTTEST_CFLAGS) -o hosttest3 hosttest3.c $(CRYPTO_SOURCE)

crypto_hosttest4:
	$(CC) $(HOSTTEST_CFLAGS) -o hosttest4 hosttest4.c $(CRYPTO_SOURCE)

crypto_hosttest5:
	$(CC) $(HOSTTEST_CFLAGS) -o hosttest5 hosttest5.c $(CRYPTO_SOURCE)

crypto_base64test:
	$(CC) $(HOSTTEST_CFLAGS) -o base64test base64test.c $(CRYPTO_SOURCE)

crypto_hosttest_clean:
	rm -f hosttest1 hosttest2 hosttest3 hosttest4 hosttest5 base64test
	rm -f $(CRYPTO_SOURCE:.c=.o)
