#!/usr/bin/expect -f
#
# This tests that the user can cast a valid ballot

set timeout -1

spawn ../../posix_sbb

expect "DISPLAY: Welcome, Voter!\r"
send -- "3\n"

expect "State change: L := FEED_BALLOT\r"
send -- "5\n"
send -- "2019+06+23+17+45:cgep2UpFCE2XLgx6QZUfW3hlVhINicNbwL9KI8UtUGM=\r"
send -- "4\n"

expect "DISPLAY:  Cast or Spoil?"
send -- "1\n"

set timeout 5
expect {
  "DISPLAY: Casting ballot.\r" { exit 0 }
  default                      { exit 1 }
}
