#!/usr/bin/expect -f
#
# This tests that after entering a valid ballot, the 
# log eventually records a timeout if no decision is made

set timeout -1

spawn ./posix_sbb

expect "DISPLAY: Welcome, Voter!\r"
send -- "3\n"

expect "State change: L := FEED_BALLOT\r"
send -- "5\n"
send -- "2019+06+23+17+45:cgep2UpFCE2XLgx6QZUfW3hlVhINicNbwL9KI8UtUGM=\r"
send -- "4\n"

set timeout 35
expect {
  "System LOG: User cast/spoil decision timeout"
    { exit 0 }
  default
    { exit 1 }
}
