# Common includes
include ../Makefile.freertos_common

DEFAULT_PROG = test_freertos

DEMO_SRC = \
    test_freertos.c \
    crypto.c \
    cbc.c \
    aes.c \
    sha2-openbsd.c \
    mode_wrappers.c

include ../Makefile.freertos_targets